package com.generic;

/**
 * Created by nckwon on 2017. 4. 2..
 */
public class MyNode2 extends Node2 {
    public MyNode2(Integer data) {
        super(data);
    }

    //Bridge method generated by the compiler
//    public void setData(Object data) {
//        setData((Integer)data);
//    }

    public void setData(Integer data) {
        System.out.println("MyNode2.setData");
        super.setData(data);
    }

    public static void main(String[] args) {
        MyNode mn = new MyNode(5);
//        Node n = mn;
//        n.setData("Hello");
//        Integer x = mn.data;

//        Node n = (MyNode)mn;
//        n.setData("Hello");
//        Integer x = (String)mn.data;
    }
}
